site_name: bassmap

site_url: https://bassneel.github.io/bassmap

repo_url: https://github.com/bassneel/bassmap

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/bassneel/bassmap/issues
    - Examples:
          - examples/Landsat_8_Tools.ipynb
          - examples/Mapomatic.ipynb
          - examples/Foliumatic.ipynb
          - examples/Select_Basemap.ipynb
          - examples/GEOG_510_Final.ipynb
    - API Reference:
          - bassmap module: bassmap.md
          - Foliumatic module: Foliumatic.md
